name: load rules

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        -
      - name: checkout bugcrowd-crowdstream
        uses: actions/checkout@v3
        with:
          name: Linuxinet/bugcrowd-crowdstream

      - name: list files
        run: |
          ls -lah bugcrowd-crowdstream